name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge staging -> main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ secrets.ITHUB_TOKEN }}
